---
title: "Problem 2"
author: "Powell Braddock"
date: "`r Sys.Date()`"
output: html_document
---

ensure you go to the console and use the command "install.packages("tidyquant")"

```{r}
library(tidyverse)
library(tidyquant)
library(timetk)
library(forcats)
library(dplyr)
```

```{r}
tq_index_options()
tq_index("SP500")
```

```{r}
daily_data <- 
  c("^GSPC","NVDA", "GOOG") %>%
  tq_get(get = "stock.prices", from = "2025-01-01", to = "2025-12-31")


```

```{r}
daily_data %>%
  ggplot(aes(x = date, y = close, color = symbol)) +
  geom_line(aes(open=open, high=high, low=low, close=close))+
  labs(title = "Time Series Chart of Adjusted Closing Prices over Time", y = "Closing Price", x = "") + 
  theme_tq()
```

```{r}
daily_data_rescaled_price <-
  daily_data %>%
  group_by(symbol) %>%
  arrange(date) %>%
  mutate(
    change_in_price_day1 = (adjusted-first(adjusted))/first(adjusted),
    daily_percent_gain=(adjusted-lag(adjusted))/lag(adjusted)
  )
daily_data_rescaled_price
```

```{r}
daily_data_rescaled_price %>%
  ggplot(aes(x=date, y=change_in_price_day1, color=symbol)) +
  geom_line()+
  labs(title= "Adjusted Closing Prices Over Time",
       x="Date",
       y="Adjusted Change in Price from Day 1 (USD)",
       color = "Ticker"
  )+
  theme_tq()+theme(legend.position = "bottom")
```

```{r}
daily_data_rescaled_price %>%
  group_by(symbol) %>%
  summarize (Min = min(daily_percent_gain, na.rm = TRUE),
             Avg = mean (daily_percent_gain, na.rm = TRUE),
             Med = median(daily_percent_gain, na.rm = TRUE),
             Max = max (daily_percent_gain, na.rm = TRUE),
             StdDev = sd(daily_percent_gain, na.rm = TRUE),
             .groups="drop")
```

```{r}
wide_daily_returns <- daily_data_rescaled_price %>%
  group_by(symbol) %>%
  arrange(date) %>%
  select(date, symbol, daily_percent_gain) %>%
  mutate(symbol = case_when(
    symbol == "^GSPC" ~ "SP500",
    symbol == "GOOG" ~ "GOOG",
    symbol == "NVDA" ~ "NVDA"
  )) %>%
  pivot_wider(names_from = symbol, values_from = daily_percent_gain) %>%
  filter(complete.cases(.))
  
```

```{r}
wide_daily_returns %>%
  ggplot(aes(x=SP500, y=GOOG))+
  geom_point()+
  labs(title= "Daily Change in SP500 and Google Returns",
       x="SP500 Daily Change Percentage",
       y="Google Daily Change Percentage")+
  theme_tq()
```

```{r}
cor_daily_matrix <- wide_daily_returns %>%
  select(SP500, GOOG, NVDA) %>%
  cor()
print(cor_daily_matrix)

## list four insights you can gather!
```

```{r}
daily_data %>%
  ggplot(aes(x = date, y = close)) +
  geom_candlestick(aes(open=open, high=high, low=low, close=close))+
  labs(title = "Time Series Chart of Adjusted Closing Prices over Time", y = "Closing Price", x = "") + 
  facet_wrap(~ symbol, scales="free_y")+
  theme_tq()
```
